# Generated by Django 5.2 on 2025-06-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='state',
            new_name='district',
        ),
    ]
