# Generated by Django 5.2 on 2025-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_state_customer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
