# Generated by Django 5.2 on 2025-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customer_zip_code_alter_store_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
