# Generated by Django 5.2 on 2025-05-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='sales.store'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store_id', 'product_id')},
        ),
    ]
