# Generated by Django 5.2 on 2025-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
