# Generated by Django 5.2 on 2025-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_product_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
